---
title: "How to setup a git repository with code, webpage and R/Binder docker" 
author: "Lieven Clement"
date: "statOmics, Ghent University (https://statomics.github.io)"
output:
    html_document:
      code_download: true    
      theme: cosmo
      toc: true
      toc_float: true
      highlight: tango
      number_sections: true
---

# Setup new repository
## Setup repository on github webpage

- Go to [GitHub](https://github.com)
- Log in to your account.
- Click the new repository button in the top-right. 
- You have an option to initialize a repository with a README file. But I do that from the command line so I do not select this option. 
- Just hit the "Create repository" button.

## Setup github repository locally

- Go to the directory where you save your github repostories
- Copy the location from the clone/download button of the repository on the github webpage here it is `git clone git@github.com:statOmics/dockerPageExample.git`
- Type `git clone git@github.com:statOmics/dockerPageExample.git`
- Write some code.
- Type `git add .` to add the files (see the typical use page).
- Type `git commit -m "first commit"` to commit your your changes to github. The -m flag is used to add the message "first commit" to indicate the changes that you add
- Type `git push origin` to add the files to your github account

##
